name: blog.takuti.me
description: This is my blog.
url: http://blog.takuti.me/

baseurl: http://blog.takuti.me

markdown: redcarpet
redcarpet:
  extensions: [tables,autolink,strikethrough]
highlighter: nil # not use pygments because of using google-code-prettify

exclude: ['Rakefile', 'tools']
include: ['.htaccess']

excerpt_separator: "<!--more-->"

permalink: /:year/:month/:title/

paginate: 30
paginate_path: 'page/:num/'

tagname:
  diary: 日記
  books: 読書
  event: イベント
  development: 開発
  vps: VPS
  chrome-extensions: 'Chrome Extensions'
  natural-language-processing: 自然言語処理
  angularjs: AngularJS
  html5-canvas: 'HTML5 Canvas'
  artificial-intelligence: 人工知能
  image-processing: 画像処理
  wordpress: WordPress
